### ISSUE TITLE
Central releases

### ISSUE THREAD

**Issue by rsertelon** [excilys/spring-log#4]
Hello,

I was wondering if I could help releasing this component on maven central.

Ping @slandelle 

Cheers,

**Comment by slandelle** [comment]
Sure, go ahead

**Comment by rsertelon** [comment]
will create a PR then ;)

**Comment by slandelle** [comment]
Thanks

**Comment by rsertelon** [comment]
Could you publish a release soon? thx ;)

**Comment by slandelle** [comment]
done

**Comment by rsertelon** [comment]
I can update the README if you want.

**Comment by slandelle** [comment]
done too

**Comment by rsertelon** [comment]
Ah nice, thanks a lot!
